services:
  - type: web
    name: opendoc-document-converter
    runtime: docker
    rootDir: services/document-converter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: starter
    region: oregon
    healthCheckPath: /health
    buildFilter:
      paths:
        - services/document-converter/**
    envVars:
      - key: API_ENABLE_BASIC_AUTH
        value: "true"
      - key: GOTENBERG_API_BASIC_AUTH_USERNAME
        sync: false
      - key: GOTENBERG_API_BASIC_AUTH_PASSWORD
        sync: false
